### ISSUE TITLE
CRAN

### ISSUE THREAD

**Issue by instantkaffee** [koncina/iosp#10]
This package has great relevance to all R users.
I am convinced that a lot of people would become hooked once you puplish on CRAN.
Any plans?

**Comment by ginolhac** [comment]
Agreed +1.  May I ask how did you discover the repo?

**Comment by instantkaffee** [comment]
@ginolhac  The hard way, manually looking up for ioslides. This is by far not the best way.  Really think the package deserves a much larger user base.

**Comment by ginolhac** [comment]
thanks, @instantkaffee. Fully agree with you. @koncina wants to fill out the README first like he did for https://github.com/koncina/unilur 
I will push him for publishing on CRAN actually both, really enjoy using those tools!

**Comment by rolandkrause** [comment]
+1. I'll help pushing.

**Comment by zkamvar** [comment]
Just saw this from Rstudio community +1 for getting this on CRAN

**Comment by ginolhac** [comment]
you got the 10 stars, now this needs to be on CRAN

**Comment by instantkaffee** [comment]
Its a pitty that this has never happened.
