### ISSUE TITLE
Adjust line spacing within box

### ISSUE THREAD

**Issue by tungttnguyen** [koncina/iosp#13]
Hello,

I was wondering if it's possible to adjust spacing between lines within a defined box? 

`### Content {.bg-blue .box-12}`

Thanks!

**Comment by koncina** [comment]
Hello,

The easiest way would be to add your own custom css class. You can for example define such a class in a css chunk like in the code below which will increase the spacing between lines (including `ul` lists) to 1.5 em:

~~~
```{css, echo = FALSE}
.my-line-space, .my-line-space ul {
  line-height: 1.5em;
}
```
### Content {.bg-blue .box-12 .my-line-space}
~~~

**Comment by tungttnguyen** [comment]
Thanks @koncina !
