### ISSUE TITLE
Change the size of the text? Align the text within the box?

### ISSUE THREAD

**Issue by tungttnguyen** [koncina/iosp#14]
Hi,

I couldn't find any where (i) how to change text size and (ii) how to align the text to the center within the box. Is it possible to align the box to the center of the slide?

Thanks!

**Comment by koncina** [comment]
**1)** In commit [ec75e34](https://github.com/koncina/iosp/commit/ec75e34b7fe6c5740cfc82bab0bb1dc623cec6cb) in the `dev` branch (`devtools::install_github("koncina/iosp@dev")`), I added the possibility to change the text size in a box using the classes `.xx-small`, `.x-small`, `.small`, `.large`, `x-large` and `.xx-large`:

![image](https://user-images.githubusercontent.com/6618930/32167375-fc57afce-bd68-11e7-9251-7b04222a4386.png)

You can of course use your own custom size adding a css chunk like this one:

~~~
```{css, echo = FALSE}
.custom-size {
  font-size: 75px;
}
```


### custom {.box-6 .offset-3 .bg-blue .custom-size}

Lorem ipsum dolor sit amet
~~~

**2)** To center the text in a box you can either use the `.centered` class (already defined in IO-slides) or, if you don't want the title being centered too, define your own class:

~~~
```{css, echo = FALSE}
.my-center :not(h3) {
  text-align: center;
}
```

### custom {.box-6 .offset-3 .bg-blue .my-center}

Lorem ipsum dolor sit amet
~~~

I will probably change this behaviour in a future commit (avoid `.centered` to affect headers and adding an explicit class to align the headers too). 

**3)** To center a box you can use the offset-x class. For example:

```
### centered box {.box-6 .offset-3}
```

If you're interested in centering the box vertically you can try to apply the middle class to the slide. You can have a look at the last slide of the template which is expected to render like this:

![image](https://user-images.githubusercontent.com/6618930/32168240-10453a58-bd6c-11e7-9503-31639410fac3.png)

**Comment by tungttnguyen** [comment]
This is awesome! Thanks so much @koncina for the help! 

One last question: is that possible to change the color of code/syntax highlighting? For example, in the attached picture, the red font makes it quite difficult to see on green/blue background. 

![codehighlightingr](https://user-images.githubusercontent.com/6590141/32180348-f36f8856-bd4e-11e7-9a6b-c3a054201662.png)

**Comment by koncina** [comment]
In the development branch (which I will merge into the master branch asap), I enhanced the rendering of the codes (the pink colour is fixed but, to enhance the contrast, the translucent background appears whiter when the background colour is dark):

![image](https://user-images.githubusercontent.com/6618930/32212388-d85c01a2-be16-11e7-838b-2e564f76a969.png)

You can also adapt this background using a css code chunk:

~~~
```{css, echo = FALSE}
code {
  padding: 0 2px;
  background-color: rgba(255, 255, 255, 0.7);
}
```
~~~

I hope that helps.

**Comment by tungttnguyen** [comment]
Thanks again @koncina !

Btw can you direct me to the source code of the slide you posted earlier? I couldn't find it anywhere 

P.S: in your previous code to center the text in the box, the bullets need to be adjusted as well

		/* Center only text inside the box */   
		.box-center-inside-text :not(h3) {    
		  text-align: center;    
		  list-style-position: inside;    
		}

**Comment by ginolhac** [comment]
on top of @tungmilan demands for the centered slide code, it would be nice to add

- code example added to the `iosp` template
- a bullet point in the `NEWS.md`

**Comment by koncina** [comment]
Hi @tungmilan,
I added the [source code](https://raw.githubusercontent.com/koncina/iosp/gh-pages/issue_014.Rmd) of the examples used earlier. You can have a look at the knitted result [here](https://koncina.github.io/iosp/issue_014.html).
As suggested by @ginolhac, I can include it in the template but as it is growing (which might not be very handy), I think it's better to show the different possibilities on a dedicated webpage (`pkgdown` or similar).

**Comment by tungttnguyen** [comment]
Thanks again @koncina ! Building a dedicated webpage is a good idea to keep things organized
