### ISSUE TITLE
shadow in R code boxes

### ISSUE THREAD

**Issue by ginolhac** [koncina/iosp#2]
is overlapping the output R code box, see example below

![image](https://cloud.githubusercontent.com/assets/710181/20786963/a9a803a2-b7a9-11e6-8094-ffac120abc88.png)

**Comment by koncina** [comment]
This was actually an intended behaviour. The dark blue code appearing in the foreground (have a look at the different shadow sizes on the right side) and the output chunk behind the code but still with a (smaller) shadow.

**Comment by ginolhac** [comment]
could we add some space in between?

**Comment by koncina** [comment]
Closing as the css code for the shadow changed since this issue was reported...
