### ISSUE TITLE
R code and results next to each other

### ISSUE THREAD

**Issue by ginolhac** [koncina/iosp#6]
and not on top of each other. Because slides are wider using the widescreen mode. That fits most sceens now. So it save space in heigth

**Comment by koncina** [comment]
You can try commit [7ca6866](https://github.com/koncina/iosp/commit/7ca686659b4cbc0934f0ac7ca2531378660a50b3) to test the new `row` chunk option. You can either set `row = TRUE` (two equal sized columns; 6 and 6) or specify a vector containing the width of the source and output chunks _i.e._ `c(source, output)` where `source + output <= 12`.

**Comment by ginolhac** [comment]
Thanks!
