### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by instantkaffee** [koncina/iosp#8]
May I suggest to add a feature, which implements a footer line, left-centered but right to the logo?

**Comment by koncina** [comment]
I added a footer option in commit [4d94675](https://github.com/koncina/iosp/commit/4d94675ff7812e773ec21e8ed21b82dbd99107b4). I merged the development lua branch to the master branch and updated the template to include a footer example (I will add a README asap). The footer option is limited as it only accepts text (_i.e._ url links will not work yet). I leave this issue open until a footer able to handle URLs is implemented.

**Comment by instantkaffee** [comment]
@koncina excellent.

**Comment by instantkaffee** [comment]
Unfortunately with the new footer version the icon is cropped now (White crop obove and below). Can you fix ?

**Comment by koncina** [comment]
I pushed the [commit b0e4822](https://github.com/koncina/iosp/commit/b0e482277cc6dfa13dab858620f5dcdf9808f728) that should fix it. The aspect ratio is now also maintained. In addition it is possible to include urls or even markdown links in the footer text. let me know if everything is rendering as expected.

**Comment by instantkaffee** [comment]
Thx, logo renders properly but footer is missing.

**Comment by ginolhac** [comment]
I gave a try and it seems to work fine for me (MacOS)
![image](https://cloud.githubusercontent.com/assets/710181/22484737/11e95cde-e803-11e6-9b1a-8d427172c74b.png)

```
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.0.136)
iosp        0.1.0   2017-01-31 Github (koncina/iosp@b0e4822)
```

**Comment by koncina** [comment]
I wasn't able to reproduce a missing footer on linux or Windows (R 3.3.2, Rstudio 1.0.136). In the last commit I fixed the detection of urls which were processed twice and thus broken. In addition, to exclude any browser related issue (unlikely), there is an example webpage [here](https://koncina.github.io/iosp/footer.html). Could you check that the footer appears as expected and that you formatted the yaml header like in the example?

**Comment by instantkaffee** [comment]
Thx, seems to work now.

**Comment by koncina** [comment]
Thank you for your feedback. I'm closing this issue as it seems to work with the links.
