### ISSUE TITLE
White/gray .bg-color

### ISSUE THREAD

**Issue by instantkaffee** [koncina/iosp#9]
May I suggest to add a white and gray background color feature?

Maybe something along:

```
.bg-gray {
  background-color: #fafafa;
}

.box.bg-gray {
  border: 2px solid #cecece;
}

.box.bg-gray > h3:first-child {
  background-color: #cecece;
  color: black;
}

.bg-white {
  background-color: #ffffff;
}

.box.bg-white {
  border: 2px solid #cecece;
}

.box.bg-white > h3:first-child {
  background-color: #cecece;
  color: black;
}
```

**Comment by koncina** [comment]
Thank you for your contribution. I added your css code in the [last commit](https://github.com/koncina/iosp/commit/593e788276239f5504792945a3b80dccbccf9eaa). I will anyway have to find a way to let a user adjust the colours without having to dig into css editing (request of [issue #1](https://github.com/koncina/iosp/issues/1)).
